apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-writ-gateway"
  labels:
    app.kubernetes.io/name: writ
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app.kubernetes.io/name: writ
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: "{{ .Values.service.port }}"
      targetPort: http
